// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLioLNrIk-pi7F0m2cDw3eJOv6GNFqtI',
    appId: '1:350062150893:android:f681afb606d2d0886ff8e4',
    messagingSenderId: '350062150893',
    projectId: 'chatter-36497',
    storageBucket: 'chatter-36497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZE54phdPxKEy3rbTMVdkIKe_ZubBOlY',
    appId: '1:350062150893:ios:10540db0c9273a5b6ff8e4',
    messagingSenderId: '350062150893',
    projectId: 'chatter-36497',
    storageBucket: 'chatter-36497.appspot.com',
    androidClientId: '350062150893-91s8j632co6lci2r4dl8fmu4uvpl1639.apps.googleusercontent.com',
    iosClientId: '350062150893-mud7dhk16ssi6f8hc8qblksnc69a82at.apps.googleusercontent.com',
    iosBundleId: 'com.casm.chatter',
  );
}
